import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/theme/colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const HERO_HEIGHT = 600;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.black },
  hero: { height: HERO_HEIGHT, width: SCREEN_WIDTH },
  safeAreaCover: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: colors.black,
  },
  heroHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 50,
  },
  heroHeaderLeft: { flexDirection: 'row', gap: 8 },
  heroHeaderRight: { flexDirection: 'row', gap: 8 },
  heroButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.black50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroButtonActive: { backgroundColor: colors.red600 },
  heroInfo: {
    position: 'absolute',
    bottom: 0,
    left: 16,
    right: 16,
    paddingBottom: 16,
  },
  heroInfoRow: { flexDirection: 'row', gap: 16 },
  heroPoster: { width: 112, aspectRatio: 2 / 3, borderRadius: 12 },
  heroInfoText: { flex: 1, justifyContent: 'flex-end' },
  statusBadge: {
    backgroundColor: colors.red600,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  statusBadgeText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  heroTitle: { fontSize: 28, fontWeight: '800', color: colors.white, marginBottom: 8 },
  heroRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  heroRatingValue: { fontSize: 20, fontWeight: '700', color: colors.white },
  heroReviewCount: { fontSize: 14, color: colors.white60 },
  heroMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  heroMeta: { fontSize: 14, color: colors.white60 },
  heroMetaDot: { fontSize: 14, color: colors.white40 },

  section: { paddingHorizontal: 16, marginTop: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.white, marginBottom: 12 },
  watchOnRow: { gap: 8 },
  watchOnButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
  },
  watchOnLogo: { width: 40, height: 40, borderRadius: 8 },
  watchOnLogoText: { fontSize: 20, fontWeight: '700', color: colors.white },
  watchOnName: { fontSize: 14, fontWeight: '600', color: colors.white },
  watchOnStream: { fontSize: 12, color: 'rgba(255,255,255,0.7)' },

  releaseAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 16,
    marginTop: 24,
    padding: 16,
    backgroundColor: colors.blue600_20,
    borderWidth: 1,
    borderColor: colors.blue600_30,
    borderRadius: 12,
  },
  releaseAlertTitle: { fontSize: 14, fontWeight: '600', color: colors.white },
  releaseAlertDate: { fontSize: 14, color: colors.blue400 },

  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 24,
    backgroundColor: colors.white5,
    borderRadius: 12,
    padding: 4,
  },
  tab: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 8 },
  tabActive: { backgroundColor: colors.red600 },
  tabText: { fontSize: 14, fontWeight: '600', color: colors.white60 },
  tabTextActive: { color: colors.white },

  tabContent: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 120 },

  overviewTab: { gap: 20 },
  synopsis: { fontSize: 15, color: 'rgba(255,255,255,0.8)', lineHeight: 24 },
  genreRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  genrePill: {
    backgroundColor: colors.white10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  genrePillText: { color: colors.white, fontSize: 14 },
  infoGrid: { flexDirection: 'row', gap: 12 },
  infoCard: {
    flex: 1,
    backgroundColor: colors.white5,
    borderRadius: 12,
    padding: 16,
    gap: 4,
  },
  infoLabel: { fontSize: 12, color: colors.white60 },
  infoValue: { fontSize: 14, fontWeight: '600', color: colors.white },
  trailerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.red600_20,
    paddingVertical: 14,
    borderRadius: 12,
  },
  trailerButtonText: { color: colors.red400, fontSize: 16, fontWeight: '600' },

  // Production Houses
  productionHousesRow: { gap: 8 },
  productionHousesLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white40,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  productionHousesList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  productionHouseChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.white10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  productionHouseLogo: { width: 24, height: 24, borderRadius: 12 },
  productionHouseName: { fontSize: 13, fontWeight: '600', color: colors.white },

  // Media Tab
  mediaTab: { gap: 24 },
  mediaSection: { gap: 12 },
  mediaSectionTitle: { fontSize: 16, fontWeight: '700', color: colors.white },
  videoRow: { flexDirection: 'row', gap: 12, paddingRight: 16 },
  videoCard: { width: 220 },
  videoThumbnailWrapper: {
    width: 220,
    height: 124,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.white5,
  },
  videoThumbnail: { width: '100%', height: '100%' },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  durationBadge: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationText: { fontSize: 11, fontWeight: '600', color: colors.white },
  videoTitle: { fontSize: 13, fontWeight: '500', color: colors.white, marginTop: 6 },

  // Poster Gallery
  posterGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  posterCard: { width: (SCREEN_WIDTH - 32 - 12) / 2 },
  posterImage: {
    width: '100%',
    aspectRatio: 2 / 3,
    borderRadius: 12,
    backgroundColor: colors.white5,
  },
  mainPosterBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  mainPosterText: { fontSize: 10, fontWeight: '700', color: colors.yellow400 },
  posterTitle: { fontSize: 12, fontWeight: '500', color: colors.white60, marginTop: 4 },

  // Video Preview Card (overview tab)
  videoPreviewCard: {
    flexDirection: 'row',
    backgroundColor: colors.white5,
    borderRadius: 12,
    overflow: 'hidden',
  },
  videoPreviewThumb: {
    width: 140,
    height: 80,
    backgroundColor: colors.white10,
  },
  videoPreviewImage: { width: '100%', height: '100%' },
  videoPreviewPlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  videoPreviewInfo: {
    flex: 1,
    padding: 12,
    justifyContent: 'center',
    gap: 4,
  },
  videoPreviewTitle: { fontSize: 14, fontWeight: '600', color: colors.white },
  videoPreviewSubtitle: { fontSize: 12, color: colors.white40 },

  // Poster Modal
  posterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  posterModalClose: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterModalContent: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 100,
    paddingBottom: 80,
  },
  posterModalImage: {
    width: SCREEN_WIDTH - 32,
    flex: 1,
    borderRadius: 12,
  },
  posterModalInfo: {
    paddingTop: 16,
    alignItems: 'center',
    gap: 4,
  },
  posterModalTitle: { fontSize: 16, fontWeight: '600', color: colors.white },
  posterModalDescription: { fontSize: 14, color: colors.white60, textAlign: 'center' },

  castTab: { gap: 16 },
  castSectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white40,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
    marginTop: 4,
  },
  castItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  castInfo: { flex: 1, gap: 2 },
  castName: { fontSize: 16, fontWeight: '600', color: colors.white },
  castRole: { fontSize: 14, color: colors.white60 },
  emptyText: { color: colors.white40, fontSize: 14, textAlign: 'center', paddingVertical: 24 },

  reviewsTab: { gap: 16 },
  ratingSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 24,
    backgroundColor: colors.white5,
    borderRadius: 12,
  },
  ratingSummaryValue: { fontSize: 36, fontWeight: '700', color: colors.white },
  ratingSummaryMax: { fontSize: 20, color: colors.white60, marginTop: 8 },
  ratingSummaryCount: { fontSize: 14, color: colors.white60, marginTop: 8, marginLeft: 4 },
  writeReviewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.red600,
    paddingVertical: 14,
    borderRadius: 12,
  },
  writeReviewText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  reviewCard: {
    padding: 16,
    backgroundColor: colors.white5,
    borderRadius: 12,
    gap: 8,
  },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  reviewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewUserName: { fontSize: 14, fontWeight: '600', color: colors.white },
  reviewDate: { fontSize: 12, color: colors.white40 },
  reviewTitle: { fontSize: 16, fontWeight: '600', color: colors.white },
  reviewBody: { fontSize: 14, color: 'rgba(255,255,255,0.7)', lineHeight: 20 },
  spoilerBadge: {
    backgroundColor: colors.orange600_20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  spoilerBadgeText: { fontSize: 12, fontWeight: '600', color: colors.orange500 },
  helpfulButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
  },
  helpfulText: { fontSize: 12, color: colors.white40 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.black95,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.zinc900,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    gap: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: { fontSize: 20, fontWeight: '700', color: colors.white },
  modalMovieInfo: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  modalPoster: { width: 56, height: 84, borderRadius: 8 },
  modalMovieTitle: { fontSize: 16, fontWeight: '600', color: colors.white },
  modalMovieMeta: { fontSize: 14, color: colors.white60 },
  modalStars: { alignItems: 'center' },
  modalInput: {
    backgroundColor: colors.white5,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.white,
  },
  modalTextArea: { height: 120 },
  spoilerToggle: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  toggleTrack: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.white20,
    justifyContent: 'center',
    padding: 2,
  },
  toggleTrackActive: { backgroundColor: colors.red600 },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.white,
  },
  toggleThumbActive: { alignSelf: 'flex-end' },
  spoilerToggleText: { fontSize: 16, color: colors.white },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalCancelText: { color: colors.white60, fontSize: 16 },
  modalSubmitButton: {
    backgroundColor: colors.red600,
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 12,
  },
  modalSubmitText: { color: colors.white, fontSize: 16, fontWeight: '600' },
});
