import { StyleSheet } from 'react-native';
import { colors as palette } from '@/theme/colors';
import type { SemanticTheme } from '@shared/themes';

export const createLoginStyles = (t: SemanticTheme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: t.background },
    scrollContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 56, paddingBottom: 40 },
    closeRow: { alignItems: 'flex-end' as const, marginBottom: 8 },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.input,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    logoContainer: { alignItems: 'center', marginBottom: 40 },
    logoFull: { height: 60, width: 167, marginBottom: 16 },
    tagline: { fontSize: 14, color: t.textTertiary, marginTop: 8 },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.input,
      borderRadius: 12,
      paddingHorizontal: 14,
      marginBottom: 12,
      height: 52,
    },
    inputIcon: { marginRight: 10 },
    input: { flex: 1, fontSize: 15, color: t.textPrimary },
    errorText: { fontSize: 13, color: palette.red500, marginBottom: 8, paddingHorizontal: 4 },
    signInButton: {
      height: 52,
      backgroundColor: palette.red600,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
    },
    buttonDisabled: { opacity: 0.6 },
    signInButtonText: { fontSize: 16, fontWeight: '700', color: t.textPrimary },
    forgotButton: { alignItems: 'center', paddingVertical: 12 },
    forgotText: { fontSize: 14, color: t.textSecondary },
    divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 16 },
    dividerLine: { flex: 1, height: 1, backgroundColor: t.textDisabled },
    dividerText: { fontSize: 12, color: t.textTertiary, marginHorizontal: 16, fontWeight: '600' },
    socialSection: { marginBottom: 16 },
    guestButton: {
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: t.textDisabled,
      alignItems: 'center',
      justifyContent: 'center',
    },
    guestButtonText: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    signUpRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 24 },
    signUpLabel: { fontSize: 14, color: t.textSecondary },
    signUpLink: { fontSize: 14, color: palette.red500, fontWeight: '600' },
  });

export const createRegisterStyles = (t: SemanticTheme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: t.background },
    scrollContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 56, paddingBottom: 40 },
    header: { marginBottom: 24 },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.input,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: { fontSize: 28, fontWeight: '800', color: t.textPrimary, marginBottom: 8 },
    subtitle: { fontSize: 15, color: t.textSecondary, marginBottom: 32 },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.input,
      borderRadius: 12,
      paddingHorizontal: 14,
      marginBottom: 12,
      height: 52,
    },
    inputIcon: { marginRight: 10 },
    input: { flex: 1, fontSize: 15, color: t.textPrimary },
    errorText: { fontSize: 13, color: '#EF4444', marginBottom: 8, paddingHorizontal: 4 },
    createButton: {
      height: 52,
      backgroundColor: '#DC2626',
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
    },
    buttonDisabled: { opacity: 0.6 },
    createButtonText: { fontSize: 16, fontWeight: '700', color: t.textPrimary },
    divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 16 },
    dividerLine: { flex: 1, height: 1, backgroundColor: t.textDisabled },
    dividerText: { fontSize: 12, color: t.textTertiary, marginHorizontal: 16, fontWeight: '600' },
    socialSection: { marginBottom: 16 },
    signInRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 24 },
    signInLabel: { fontSize: 14, color: t.textSecondary },
    signInLink: { fontSize: 14, color: '#EF4444', fontWeight: '600' },
  });
