import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
import type { SemanticTheme } from '@shared/themes';

export const createStyles = (t: SemanticTheme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: t.background },
    safeAreaCover: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 100,
      backgroundColor: t.background,
    },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    header: {
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    headerTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.input,
      alignItems: 'center',
      justifyContent: 'center',
    },
    screenTitle: {
      fontSize: 30,
      fontWeight: '700',
      color: t.textPrimary,
    },
    searchInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.input,
      borderRadius: 24,
      paddingHorizontal: 16,
      height: 48,
      borderWidth: 1,
      borderColor: t.border,
    },
    searchIcon: { marginRight: 8 },
    searchInput: { flex: 1, fontSize: 16, color: t.textPrimary },
    tabRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      gap: 8,
      marginBottom: 12,
    },
    tabButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: t.surfaceElevated,
      alignItems: 'center',
    },
    tabButtonActive: { backgroundColor: colors.red600 },
    tabButtonText: { fontSize: 13, fontWeight: '600', color: t.textSecondary },
    tabButtonTextActive: { color: colors.white },
    filterBar: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      gap: 8,
      marginBottom: 8,
    },
    filterButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: t.input,
    },
    sortButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: t.input,
    },
    filterBarText: { color: t.textPrimary, fontSize: 14, fontWeight: '500' },
    filterCountBadge: {
      backgroundColor: colors.red600,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterCountText: { color: colors.white, fontSize: 10, fontWeight: '700' },
    sortDropdown: {
      position: 'absolute',
      top: 165,
      right: 16,
      backgroundColor: t.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: t.border,
      zIndex: 100,
    },
    sortOption: { paddingHorizontal: 16, paddingVertical: 10 },
    sortOptionActive: { backgroundColor: colors.red600 },
    sortOptionText: { color: t.textSecondary, fontSize: 14 },
    sortOptionTextActive: { color: colors.white },
    activePills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    activePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.red600_20,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
    },
    activePillText: { color: colors.red400, fontSize: 13 },
    clearAllLink: { color: colors.red500, fontSize: 13, textDecorationLine: 'underline' },
    movieCountRow: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: t.borderSubtle,
    },
    movieCountText: {
      fontSize: 13,
      color: t.textTertiary,
    },
    gridContent: { paddingHorizontal: 16, paddingBottom: 100 },
    gridRow: { gap: 16, marginBottom: 16 },
    gridItem: { flex: 1 },
    gridPoster: {
      aspectRatio: 2 / 3,
      borderRadius: 16,
      overflow: 'hidden',
      marginBottom: 8,
    },
    gridBadgeLeft: { position: 'absolute', top: 10, left: 10 },
    gridBadgeRight: {
      position: 'absolute',
      top: 10,
      right: 10,
      flexDirection: 'row',
      gap: 4,
    },
    gridRating: {
      position: 'absolute',
      bottom: 10,
      left: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: t.overlayHeavy,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    gridRatingText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' },
    gridTitle: { fontSize: 14, fontWeight: '600', color: t.textPrimary },

    // Modal
    modalOverlay: { flex: 1, backgroundColor: t.overlayHeavy, justifyContent: 'flex-end' },
    modalContent: {
      backgroundColor: t.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      maxHeight: '80%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    modalTitle: { fontSize: 20, fontWeight: '700', color: t.textPrimary },
    modalSectionTitle: { fontSize: 16, fontWeight: '600', color: t.textPrimary, marginBottom: 12 },
    platformGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    platformButton: {
      width: '47%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      borderRadius: 12,
    },
    platformName: { fontSize: 13, color: t.textPrimary, flex: 1 },
    platformCheck: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: 'rgba(0,0,0,0.3)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    genreGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    genrePill: {
      backgroundColor: t.input,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
    },
    genrePillActive: { backgroundColor: t.textPrimary },
    genrePillText: { color: t.textSecondary, fontSize: 14 },
    genrePillTextActive: { color: t.background, fontWeight: '700' },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 24,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: t.border,
    },
    clearFiltersText: { color: t.textSecondary, fontSize: 14 },
    showResultsButton: {
      backgroundColor: colors.red600,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
    },
    showResultsText: { color: colors.white, fontSize: 16, fontWeight: '600' },
    footerLoader: {
      paddingVertical: 24,
      alignItems: 'center',
    },
  });
