import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/theme/colors';
import type { SemanticTheme } from '@shared/themes';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const HERO_HEIGHT = 600;

export const createStyles = (t: SemanticTheme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: t.background },
    hero: { height: HERO_HEIGHT, width: SCREEN_WIDTH, overflow: 'hidden' as const },
    heroHeader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      zIndex: 50,
    },
    heroHeaderLeft: { flexDirection: 'row', gap: 8 },
    heroHeaderRight: { flexDirection: 'row', gap: 8 },
    heroButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.overlay,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroButtonActive: { backgroundColor: colors.red600 },
    heroInfo: {
      position: 'absolute',
      bottom: 0,
      left: 16,
      right: 16,
      paddingBottom: 16,
    },
    heroInfoRow: { flexDirection: 'row', gap: 16 },
    heroPoster: { width: 112, aspectRatio: 2 / 3, borderRadius: 12 },
    heroInfoText: { flex: 1, justifyContent: 'flex-end' },
    statusBadge: {
      backgroundColor: colors.red600,
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: 12,
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    statusBadgeText: {
      color: colors.white,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    heroTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: '#FFFFFF',
      marginBottom: 8,
      textShadowColor: 'rgba(0,0,0,0.6)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 6,
    },
    heroRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
    heroRatingValue: { fontSize: 20, fontWeight: '700', color: '#FFFFFF' },
    heroReviewCount: { fontSize: 14, color: 'rgba(255,255,255,0.7)' },
    heroMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    heroMeta: { fontSize: 14, color: 'rgba(255,255,255,0.7)' },
    heroMetaDot: { fontSize: 14, color: 'rgba(255,255,255,0.4)' },

    section: { paddingHorizontal: 16, marginTop: 24 },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: t.textPrimary, marginBottom: 12 },
    watchOnRow: { gap: 8 },
    watchOnButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 12,
    },
    watchOnLogo: { width: 40, height: 40, borderRadius: 8 },
    watchOnLogoText: { fontSize: 20, fontWeight: '700', color: colors.white },
    watchOnName: { fontSize: 14, fontWeight: '600', color: colors.white },
    watchOnStream: { fontSize: 12, color: t.textSecondary },

    releaseAlert: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginHorizontal: 16,
      marginTop: 24,
      padding: 16,
      backgroundColor: colors.blue600_20,
      borderWidth: 1,
      borderColor: colors.blue600_30,
      borderRadius: 12,
    },
    releaseAlertTitle: { fontSize: 14, fontWeight: '600', color: t.textPrimary },
    releaseAlertDate: { fontSize: 14, color: colors.blue400 },

    tabBar: {
      flexDirection: 'row',
      marginHorizontal: 16,
      marginTop: 24,
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
      padding: 4,
    },
    tab: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 8, zIndex: 1 },
    tabIndicator: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      left: 4,
      borderRadius: 8,
      backgroundColor: colors.red600,
    },
    tabText: { fontSize: 14, fontWeight: '600', color: t.textSecondary },
    tabTextActive: { color: colors.white },

    tabContent: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 120 },

    overviewTab: { gap: 20 },
    tagline: { fontSize: 14, fontStyle: 'italic', color: t.textSecondary, lineHeight: 20 },
    synopsis: { fontSize: 15, color: t.textPrimary, lineHeight: 24 },
    tmdbRatingRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    tmdbRatingText: { fontSize: 13, color: t.textSecondary, fontWeight: '500' },
    collectionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: t.input,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      alignSelf: 'flex-start',
    },
    collectionBadgeText: { fontSize: 13, fontWeight: '600', color: t.textPrimary },
    genreRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    genrePill: {
      backgroundColor: t.input,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    genrePillText: { color: t.textPrimary, fontSize: 14 },
    infoGrid: { flexDirection: 'row', gap: 12 },
    infoCard: {
      flex: 1,
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
      padding: 16,
      gap: 4,
    },
    infoLabel: { fontSize: 12, color: t.textSecondary },
    infoValue: { fontSize: 14, fontWeight: '600', color: t.textPrimary },

    // Production Houses
    productionHousesRow: { gap: 8 },
    productionHousesLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: t.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    productionHousesList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    productionHouseChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: t.input,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
    },
    productionHouseLogo: { width: 24, height: 24, borderRadius: 12 },
    productionHouseName: { fontSize: 13, fontWeight: '600', color: t.textPrimary },

    // Media Summary Card (overview tab)
    mediaSummaryCard: {
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
      overflow: 'hidden',
    },
    mediaSummaryThumb: {
      width: '100%',
      aspectRatio: 16 / 9,
      backgroundColor: t.input,
    },
    mediaSummaryImage: { width: '100%', height: '100%' },
    mediaSummaryPlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.3)',
    },
    mediaSummaryInfo: { padding: 12, gap: 4 },
    mediaSummaryText: { fontSize: 14, fontWeight: '500', color: t.textSecondary },
    mediaSummaryCtaRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    mediaSummaryCtaText: { fontSize: 14, fontWeight: '600', color: colors.red400 },

    castTab: { gap: 16 },
    castSectionLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: t.textTertiary,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 4,
      marginTop: 4,
    },
    castItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    castInfo: { flex: 1, gap: 2 },
    castName: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    castRole: { fontSize: 14, color: t.textSecondary },
    emptyText: { color: t.textTertiary, fontSize: 14, textAlign: 'center', paddingVertical: 24 },

    reviewsTab: { gap: 16 },
    ratingSummary: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 24,
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
    },
    ratingSummaryValue: { fontSize: 36, fontWeight: '700', color: t.textPrimary },
    ratingSummaryMax: { fontSize: 20, color: t.textSecondary, marginTop: 8 },
    ratingSummaryCount: { fontSize: 14, color: t.textSecondary, marginTop: 8, marginLeft: 4 },
    writeReviewButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.red600,
      paddingVertical: 14,
      borderRadius: 12,
    },
    writeReviewText: { color: colors.white, fontSize: 16, fontWeight: '600' },
    reviewCard: {
      padding: 16,
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
      gap: 8,
    },
    reviewHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    reviewHeaderInfo: { flex: 1 },
    reviewAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.input,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reviewUserName: { fontSize: 14, fontWeight: '600', color: t.textPrimary },
    reviewDate: { fontSize: 12, color: t.textTertiary },
    reviewTitle: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    reviewBody: { fontSize: 14, color: t.textSecondary, lineHeight: 20 },
    spoilerBadge: {
      backgroundColor: colors.orange600_20,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    spoilerBadgeText: { fontSize: 12, fontWeight: '600', color: colors.orange500 },
    helpfulButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      alignSelf: 'flex-start',
    },
    helpfulText: { fontSize: 12, color: t.textTertiary },

    // Modal
    modalOverlay: {
      flex: 1,
      backgroundColor: t.overlayHeavy,
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: t.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      gap: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modalTitle: { fontSize: 20, fontWeight: '700', color: t.textPrimary },
    modalMovieInfo: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    modalPoster: { width: 56, height: 84, borderRadius: 8 },
    modalMovieTitle: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    modalMovieMeta: { fontSize: 14, color: t.textSecondary },
    modalStars: { alignItems: 'center' },
    modalInput: {
      backgroundColor: t.surfaceElevated,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 16,
      color: t.textPrimary,
    },
    modalTextArea: { height: 120 },
    spoilerToggle: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    toggleTrack: {
      width: 48,
      height: 28,
      borderRadius: 14,
      backgroundColor: t.inputActive,
      justifyContent: 'center',
      padding: 2,
    },
    toggleTrackActive: { backgroundColor: colors.red600 },
    toggleThumb: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.white,
    },
    toggleThumbActive: { alignSelf: 'flex-end' },
    spoilerToggleText: { fontSize: 16, color: t.textPrimary },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modalCancelText: { color: t.textSecondary, fontSize: 16 },
    modalSubmitButton: {
      backgroundColor: colors.red600,
      paddingHorizontal: 32,
      paddingVertical: 12,
      borderRadius: 12,
    },
    modalSubmitText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  });
