import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
import type { SemanticTheme } from '@shared/themes';

export const createStyles = (t: SemanticTheme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: t.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.input,
      borderRadius: 24,
      paddingHorizontal: 12,
      height: 44,
      gap: 8,
    },
    searchInput: { flex: 1, fontSize: 16, color: t.textPrimary },
    cancelText: { color: t.textSecondary, fontSize: 16 },
    noQuery: { paddingHorizontal: 16, paddingTop: 16 },
    recentSection: { marginBottom: 32 },
    recentHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    recentTitle: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    clearText: { color: colors.red500, fontSize: 14 },
    recentPills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    recentPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: t.surfaceElevated,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
    },
    recentPillInner: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    recentPillText: { color: t.textPrimary, fontSize: 14 },
    resultsCount: {
      fontSize: 14,
      color: t.textSecondary,
      marginBottom: 12,
      paddingHorizontal: 16,
    },
    resultsList: { paddingHorizontal: 16, paddingBottom: 100 },
    trendingSection: { marginTop: 24 },
    trendingHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 16,
    },
    trendingTitle: { fontSize: 16, fontWeight: '600', color: t.textPrimary },
    trendingItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 8,
    },
    trendingRank: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(239,68,68,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    trendingRankText: { fontSize: 13, fontWeight: '700', color: colors.red500 },
    trendingPoster: { width: 48, height: 72, borderRadius: 8 },
    trendingInfo: { flex: 1, gap: 4 },
    trendingMovieTitle: { fontSize: 15, fontWeight: '600', color: t.textPrimary },
    trendingMeta: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    trendingRating: { fontSize: 12, color: t.textSecondary },
    trendingDot: { fontSize: 12, color: t.textTertiary },
    trendingReviews: { fontSize: 12, color: t.textSecondary },
    filterRow: { maxHeight: 44, marginBottom: 8 },
    filterRowContent: { paddingHorizontal: 16, gap: 8 },
    filterChip: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: t.input,
    },
    filterChipActive: { backgroundColor: colors.red600 },
    filterChipText: { fontSize: 13, fontWeight: '600', color: t.textSecondary },
    filterChipTextActive: { color: colors.white },
    sectionDivider: {
      height: 1,
      backgroundColor: t.border,
      marginVertical: 8,
      marginHorizontal: 16,
    },
  });
