import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.black },
  safeAreaCover: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: colors.black,
  },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  screenTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: colors.white,
    marginBottom: 16,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white10,
    borderRadius: 24,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: colors.white10,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: colors.white },
  tabRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 12,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.white5,
    alignItems: 'center',
  },
  tabButtonActive: { backgroundColor: colors.red600 },
  tabButtonText: { fontSize: 13, fontWeight: '600', color: colors.white50 },
  tabButtonTextActive: { color: colors.white },
  filterBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 8,
  },
  filterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.white10,
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.white10,
  },
  filterBarText: { color: colors.white, fontSize: 14, fontWeight: '500' },
  filterCountBadge: {
    backgroundColor: colors.red600,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterCountText: { color: colors.white, fontSize: 10, fontWeight: '700' },
  sortDropdown: {
    position: 'absolute',
    top: 165,
    right: 16,
    backgroundColor: colors.zinc900,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.white10,
    zIndex: 100,
  },
  sortOption: { paddingHorizontal: 16, paddingVertical: 10 },
  sortOptionActive: { backgroundColor: colors.red600 },
  sortOptionText: { color: colors.white60, fontSize: 14 },
  sortOptionTextActive: { color: colors.white },
  activePills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  activePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.red600_20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  activePillText: { color: colors.red400, fontSize: 13 },
  clearAllLink: { color: colors.red500, fontSize: 13, textDecorationLine: 'underline' },
  movieCountRow: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.white5,
  },
  movieCountText: {
    fontSize: 13,
    color: colors.white40,
  },
  gridContent: { paddingHorizontal: 16, paddingBottom: 100 },
  gridRow: { gap: 16, marginBottom: 16 },
  gridItem: { flex: 1 },
  gridPoster: {
    aspectRatio: 2 / 3,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 8,
  },
  gridBadgeLeft: { position: 'absolute', top: 10, left: 10 },
  gridBadgeRight: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    gap: 4,
  },
  gridPlatformIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridPlatformText: { color: colors.white, fontSize: 10, fontWeight: '700' },
  gridRating: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.black80,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  gridRatingText: { color: colors.white, fontSize: 12, fontWeight: '600' },
  gridTitle: { fontSize: 14, fontWeight: '600', color: colors.white },

  // Modal
  modalOverlay: { flex: 1, backgroundColor: colors.black95, justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: colors.zinc900,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: { fontSize: 20, fontWeight: '700', color: colors.white },
  modalSectionTitle: { fontSize: 16, fontWeight: '600', color: colors.white, marginBottom: 12 },
  platformGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  platformButton: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
  },
  platformLogo: { fontSize: 18, fontWeight: '700', color: colors.white },
  platformName: { fontSize: 13, color: colors.white, flex: 1 },
  platformCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  genreGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  genrePill: {
    backgroundColor: colors.white10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  genrePillActive: { backgroundColor: colors.white },
  genrePillText: { color: 'rgba(255,255,255,0.7)', fontSize: 14 },
  genrePillTextActive: { color: colors.black, fontWeight: '700' },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.white10,
  },
  clearFiltersText: { color: colors.white60, fontSize: 14 },
  showResultsButton: {
    backgroundColor: colors.red600,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  showResultsText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  footerLoader: {
    paddingVertical: 24,
    alignItems: 'center',
  },
});
