-- Force Row Level Security on all tables

ALTER TABLE movies FORCE ROW LEVEL SECURITY;
ALTER TABLE movie_cast FORCE ROW LEVEL SECURITY;
ALTER TABLE platforms FORCE ROW LEVEL SECURITY;
ALTER TABLE ott_releases FORCE ROW LEVEL SECURITY;
ALTER TABLE profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE watchlists FORCE ROW LEVEL SECURITY;
ALTER TABLE reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE push_tokens FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_queue FORCE ROW LEVEL SECURITY;

-- Additional indexes for common queries
