tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#003061",
              "on-primary-container": "#fff7f6",
              "surface-container-lowest": "#0e0e0e",
              "surface-container-low": "#1c1b1b",
              "surface-container-high": "#2a2a2a",
              "on-background": "#e5e2e1",
              "tertiary": "#a7c8ff",
              "surface": "#131313",
              "surface-dim": "#131313",
              "on-surface": "#e5e2e1",
              "on-error-container": "#ffdad6",
              "secondary-fixed-dim": "#ffb4aa",
              "surface-container-highest": "#353534",
              "outline": "#af8782",
              "surface-variant": "#353534",
              "surface-bright": "#3a3939",
              "tertiary-fixed-dim": "#a7c8ff",
              "surface-container": "#201f1f",
              "primary-container": "#e50914",
              "on-secondary-container": "#ff9f93",
              "secondary": "#ffb4aa",
              "primary": "#ffb4aa",
              "inverse-surface": "#e5e2e1",
              "outline-variant": "#5e3f3b",
              "on-tertiary-container": "#f8f9ff",
              "tertiary-fixed": "#d5e3ff",
              "surface-tint": "#ffb4aa",
              "on-secondary-fixed": "#410001",
              "tertiary-container": "#0072d7",
              "primary-fixed-dim": "#ffb4aa",
              "primary-fixed": "#ffdad5",
              "on-secondary-fixed-variant": "#8e1210",
              "on-secondary": "#690003",
              "on-primary": "#690003",
              "on-error": "#690005",
              "inverse-on-surface": "#313030",
              "secondary-fixed": "#ffdad5",
              "on-surface-variant": "#e9bcb6",
              "on-tertiary-fixed-variant": "#004689",
              "error-container": "#93000a",
              "secondary-container": "#921512",
              "inverse-primary": "#c0000c",
              "on-tertiary-fixed": "#001b3c",
              "on-primary-fixed": "#410001",
              "on-primary-fixed-variant": "#930007",
              "background": "#131313",
              "error": "#ffb4ab"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Epilogue"],
              "body": ["Manrope"],
              "label": ["Manrope"]
      }
    },
  },
}
